name: zarosh
description: An expansive game world for your powerd6 campaign.
version: 1.0.0
homepage: https://github.com/powerd6/zarosh
issue_tracker: https://github.com/powerd6/zarosh/issues

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  powerbook: ^1.0.3
  powerd6: ^1.0.0

dev_dependencies:
  lints: ^1.0.0
